use Mix.Config

# Configure your database
config :dev_challenge_ryan, DevChallengeRyan.Repo,
  username: "postgres",
  password: "postgres",
  database: "dev_challenge_ryan_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :dev_challenge_ryan, DevChallengeRyanWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :dev_challenge_ryan, DevChallengeRyanWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/dev_challenge_ryan_web/(live|views)/.*(ex)$",
      ~r"lib/dev_challenge_ryan_web/templates/.*(eex)$"
    ]
  ]

config :dev_challenge_ryan, DevChallengeRyanWeb.UtilityContext,
  blocknative_url: "https://api.blocknative.com/",
  api_key_2: "d8ebd14b-1662-4422-8ea5-b6a4be21bedf",
  slack_token_2: "xoxb-1898995580646-1902698037429-lhVxZoe2GJDCAMJ8DVu4A7M4",
  api_key: "2457ae16-d5f9-4e61-89b6-fd68a1a90482",
  slack_url: "https://slack.com/",
  slack_webhook: "https://hooks.slack.com/services/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"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
